spring:
  application:
    name: portfolio

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5433/personal_db}
    username: ${DB_USERNAME:personal_user}
    password: ${DB_PASSWORD:personal_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false

    hibernate:
      ddl-auto: validate

    show-sql: true

    properties:
      hibernate:
        format_sql: true